spring.application.name=backend

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sge
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Flyway (Migrações)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
