spring.application.name=sge

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sge
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true